export const ERROR_CODES = {
	VALIDATION: "VALIDATION",
	DATABASE: {
		NOT_FOUND: "NOT_FOUND",
		INVALID_QUERY: "INVALID_QUERY",
	},
	PARSE: {
		FAILED: "PARSE_FAILED",
	},
	CONNECTION: "CONNECTION_REFUSED",
};
