export interface Leader {
	id: number;
	name: string;
	code: string;
	active: boolean;
	civilization_id: number;
	image?: string;
}

export const LEADERS: Array<Leader> = [
	{
		id: 2,
		name: "Teddy Roosevelt (Bull Moose)",
		code: "LEADER_T_ROOSEVELT",
		active: true,
		civilization_id: 1,
	},
	{
		id: 3,
		name: "Teddy Roosevelt (Rough Rider)",
		code: "LEADER_T_ROOSEVELT_ROUGHRIDER",
		active: true,
		civilization_id: 1,
		image: "https://static.wikia.nocookie.net/civilization/images/c/c3/Teddy_Roosevelt_%28Rough_Rider%29_%28Civ6%29.png",
	},
	{
		id: 4,
		name: "Abraham Lincoln",
		code: "LEADER_ABRAHAM_LINCOLN",
		active: true,
		civilization_id: 1,
		image: "https://static.wikia.nocookie.net/civilization/images/9/97/Abraham_Lincoln_(Civ6).png",
	},
	{
		id: 5,
		name: "Saladin (Vizier)",
		code: "LEADER_SALADIN",
		active: true,
		civilization_id: 2,
	},
	{
		id: 6,
		name: "Saladin (Sultan)",
		code: "LEADER_SALADIN_ALT",
		active: true,
		civilization_id: 2,
	},
	{
		id: 7,
		name: "John Curtin",
		code: "LEADER_JOHN_CURTIN",
		active: true,
		civilization_id: 3,
	},
	{
		id: 8,
		name: "Montezuma",
		code: "LEADER_MONTEZUMA",
		active: true,
		civilization_id: 4,
	},
	{
		id: 9,
		name: "Hammurabi",
		code: "LEADER_HAMMURABI",
		active: true,
		civilization_id: 5,
	},
	{
		id: 10,
		name: "Pedro II",
		code: "LEADER_PEDRO",
		active: true,
		civilization_id: 6,
	},
	{
		id: 11,
		name: "Basil II",
		code: "LEADER_BASIL",
		active: true,
		civilization_id: 7,
	},
	{
		id: 12,
		name: "Theodora",
		code: "LEADER_THEODORA",
		active: true,
		civilization_id: 7,
	},
	{
		id: 13,
		name: "Wilfrid Laurier",
		code: "LEADER_LAURIER",
		active: true,
		civilization_id: 8,
	},
	{
		id: 14,
		name: "Qin Shi Huang (Mandate of Heaven)",
		code: "LEADER_QIN",
		active: true,
		civilization_id: 9,
	},
	{
		id: 15,
		name: "Qin Shi Huang (Unifier)",
		code: "LEADER_QIN_ALT",
		active: true,
		civilization_id: 9,
	},
	{
		id: 16,
		name: "Kublai Khan (Chinese)",
		code: "LEADER_KUBLAI_KHAN_CHINA",
		active: true,
		civilization_id: 9,
	},
	{
		id: 17,
		name: "Yongle",
		code: "LEADER_YONGLE",
		active: true,
		civilization_id: 9,
	},
	{
		id: 18,
		name: "Wu Zetian",
		code: "LEADER_WU_ZETIAN",
		active: true,
		civilization_id: 9,
	},
	{
		id: 19,
		name: "Poundmaker",
		code: "LEADER_POUNDMAKER",
		active: true,
		civilization_id: 10,
	},
	{
		id: 20,
		name: "Wilhelmina",
		code: "LEADER_WILHELMINA",
		active: true,
		civilization_id: 11,
	},
	{
		id: 21,
		name: "Cleopatra (Egyptian)",
		code: "LEADER_CLEOPATRA",
		active: true,
		civilization_id: 12,
	},
	{
		id: 22,
		name: "Cleopatra (Ptolemaic)",
		code: "LEADER_CLEOPATRA_ALT",
		active: true,
		civilization_id: 12,
	},
	{
		id: 23,
		name: "Ramses II",
		code: "LEADER_RAMSES",
		active: true,
		civilization_id: 12,
	},
	{
		id: 24,
		name: "Victoria (Age of Empire)",
		code: "LEADER_VICTORIA",
		active: true,
		civilization_id: 13,
		image: "https://static.wikia.nocookie.net/civilization/images/5/53/Victoria_%28Civ6%29.png",
	},
	{
		id: 25,
		name: "Victoria (Age of Steam)",
		code: "LEADER_VICTORIA_ALT",
		active: true,
		civilization_id: 13,
		image: "https://static.wikia.nocookie.net/civilization/images/8/8d/Victoria_%28Age_of_Steam%29_%28Civ6%29.png",
	},
	{
		id: 26,
		name: "Eleanor of Aquitaine (English)",
		code: "LEADER_ELEANOR_ENGLAND",
		active: true,
		civilization_id: 13,
	},
	{
		id: 27,
		name: "Elizabeth I",
		code: "LEADER_ELIZABETH",
		active: true,
		civilization_id: 13,
	},
	{
		id: 28,
		name: "Menelik II",
		code: "LEADER_MENELIK",
		active: true,
		civilization_id: 14,
	},
	{
		id: 29,
		name: "Catherine de Medici (Black Queen)",
		code: "LEADER_CATHERINE_DE_MEDICI",
		active: true,
		civilization_id: 15,
	},
	{
		id: 30,
		name: "Catherine de Medici (Magnificence)",
		code: "LEADER_CATHERINE_DE_MEDICI_ALT",
		active: true,
		civilization_id: 15,
	},
	{
		id: 31,
		name: "Eleanor of Aquitaine (French)",
		code: "LEADER_ELEANOR_FRANCE",
		active: true,
		civilization_id: 15,
	},
	{
		id: 32,
		name: "Ambiorix",
		code: "LEADER_AMBIORIX",
		active: true,
		civilization_id: 16,
	},
	{
		id: 33,
		name: "Tamar",
		code: "LEADER_TAMAR",
		active: true,
		civilization_id: 17,
	},
	{
		id: 34,
		name: "Frederick Barbarossa",
		code: "LEADER_BARBAROSSA",
		active: true,
		civilization_id: 18,
	},
	{
		id: 35,
		name: "Ludwig II",
		code: "LEADER_LUDWIG",
		active: true,
		civilization_id: 18,
	},
	{
		id: 36,
		name: "Simón Bolívar",
		code: "LEADER_SIMON_BOLIVAR",
		active: true,
		civilization_id: 19,
	},
	{
		id: 37,
		name: "Pericles",
		code: "LEADER_PERICLES",
		active: true,
		civilization_id: 20,
	},
	{
		id: 38,
		name: "Gorgo",
		code: "LEADER_GORGO",
		active: true,
		civilization_id: 20,
	},
	{
		id: 39,
		name: "Matthias Corvinus",
		code: "LEADER_MATTHIAS_CORVINUS",
		active: true,
		civilization_id: 21,
	},
	{
		id: 40,
		name: "Pachacuti",
		code: "LEADER_PACHACUTI",
		active: true,
		civilization_id: 22,
	},
	{
		id: 41,
		name: "Gandhi",
		code: "LEADER_GANDHI",
		active: true,
		civilization_id: 23,
	},
	{
		id: 42,
		name: "Chandragupta",
		code: "LEADER_CHANDRAGUPTA",
		active: true,
		civilization_id: 23,
	},
	{
		id: 43,
		name: "Gitarja",
		code: "LEADER_GITARJA",
		active: true,
		civilization_id: 24,
	},
	{
		id: 44,
		name: "Hojo Tokimune",
		code: "LEADER_HOJO",
		active: true,
		civilization_id: 25,
	},
	{
		id: 45,
		name: "Tokugawa",
		code: "LEADER_TOKUGAWA",
		active: true,
		civilization_id: 25,
	},
	{
		id: 46,
		name: "Jayavarman VII",
		code: "LEADER_JAYAVARMAN",
		active: true,
		civilization_id: 26,
	},
	{
		id: 47,
		name: "Mvemba a Nzinga",
		code: "LEADER_MVEMBA",
		active: true,
		civilization_id: 27,
	},
	{
		id: 48,
		name: "Nzinga Mbande",
		code: "LEADER_NZINGA_MBANDE",
		active: true,
		civilization_id: 27,
	},
	{
		id: 49,
		name: "Seondeok",
		code: "LEADER_SEONDEOK",
		active: true,
		civilization_id: 28,
	},
	{
		id: 50,
		name: "Sejong",
		code: "LEADER_SEJONG",
		active: true,
		civilization_id: 28,
	},
	{
		id: 51,
		name: "Alexander",
		code: "LEADER_ALEXANDER",
		active: true,
		civilization_id: 29,
	},
	{
		id: 52,
		name: "Mansa Musa",
		code: "LEADER_MANSA_MUSA",
		active: true,
		civilization_id: 30,
	},
	{
		id: 53,
		name: "Sundiata Keita",
		code: "LEADER_SUNDIATA_KEITA",
		active: true,
		civilization_id: 30,
	},
	{
		id: 54,
		name: "Kupe",
		code: "LEADER_KUPE",
		active: true,
		civilization_id: 31,
	},
	{
		id: 55,
		name: "Lautaro",
		code: "LEADER_LAUTARO",
		active: true,
		civilization_id: 32,
	},
	{
		id: 56,
		name: "Lady Six Sky",
		code: "LEADER_LADY_SIX_SKY",
		active: true,
		civilization_id: 33,
	},
	{
		id: 57,
		name: "Genghis Khan",
		code: "LEADER_GENGHIS_KHAN",
		active: true,
		civilization_id: 34,
	},
	{
		id: 58,
		name: "Kublai Khan (Mongolian)",
		code: "LEADER_KUBLAI_KHAN_MONGOLIA",
		active: true,
		civilization_id: 34,
	},
	{
		id: 59,
		name: "Harald Hardrada (Konge)",
		code: "LEADER_HARDRADA",
		active: true,
		civilization_id: 35,
	},
	{
		id: 60,
		name: "Harald Hardrada (Varangian)",
		code: "LEADER_HARALD_ALT",
		active: true,
		civilization_id: 35,
	},
	{
		id: 61,
		name: "Amanitore",
		code: "LEADER_AMANITORE",
		active: true,
		civilization_id: 36,
	},
	{
		id: 62,
		name: "Suleiman (Kanuni)",
		code: "LEADER_SULEIMAN",
		active: true,
		civilization_id: 37,
	},
	{
		id: 63,
		name: "Suleiman (Muhteşem)",
		code: "LEADER_SULEIMAN_ALT",
		active: true,
		civilization_id: 37,
	},
	{
		id: 64,
		name: "Cyrus",
		code: "LEADER_CYRUS",
		active: true,
		civilization_id: 38,
	},
	{
		id: 65,
		name: "Nader Shah",
		code: "LEADER_NADER_SHAH",
		active: true,
		civilization_id: 38,
	},
	{
		id: 66,
		name: "Dido",
		code: "LEADER_DIDO",
		active: true,
		civilization_id: 39,
	},
	{
		id: 67,
		name: "Jadwiga",
		code: "LEADER_JADWIGA",
		active: true,
		civilization_id: 40,
	},
	{
		id: 68,
		name: "João III",
		code: "LEADER_JOAO_III",
		active: true,
		civilization_id: 41,
	},
	{
		id: 69,
		name: "Trajan",
		code: "LEADER_TRAJAN",
		active: true,
		civilization_id: 42,
	},
	{
		id: 70,
		name: "Julius Caesar",
		code: "LEADER_JULIUS_CAESAR",
		active: true,
		civilization_id: 42,
	},
	{
		id: 71,
		name: "Peter",
		code: "LEADER_PETER_GREAT",
		active: true,
		civilization_id: 43,
	},
	{
		id: 72,
		name: "Robert the Bruce",
		code: "LEADER_ROBERT_THE_BRUCE",
		active: true,
		civilization_id: 44,
	},
	{
		id: 73,
		name: "Tomyris",
		code: "LEADER_TOMYRIS",
		active: true,
		civilization_id: 45,
	},
	{
		id: 74,
		name: "Philip II",
		code: "LEADER_PHILIP_II",
		active: true,
		civilization_id: 46,
	},
	{
		id: 75,
		name: "Gilgamesh",
		code: "LEADER_GILGAMESH",
		active: true,
		civilization_id: 47,
	},
	{
		id: 76,
		name: "Kristina",
		code: "LEADER_KRISTINA",
		active: true,
		civilization_id: 48,
	},
	{
		id: 77,
		name: "Bà Triệu",
		code: "LEADER_LADY_TRIEU",
		active: true,
		civilization_id: 49,
	},
	{
		id: 78,
		name: "Shaka",
		code: "LEADER_SHAKA",
		active: true,
		civilization_id: 50,
	},
];
